name: Build and Release

on:
  # 指明要运行的分支
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build

      # 执行 semantic-release 发布包
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd ./packages/react && npx semantic-release
